---
title: "googleVis"
author: "Michael Harrison"
date: "July 11, 2017"
output: html_document
---

#Motion Charts

```{r gv, results = "asis", cache=TRUE}
suppressPackageStartupMessages(library(googleVis))
M <- gvisMotionChart(Fruits, idvar = "Fruit", timevar = "Year",
                     options = list(width = 600, height = 400))
print(M, "chart")
```

#Plots on Maps

```{r}
G <- gvisGeoChart(Exports, locationvar = "Country",
                  colorvar = "Profit", options=list(width=600, height=400))
```

## Setting more options
https://developers.google.com/chart/interactive/docs/gallery/geochart

#Line Chart
```{r}
df <- data.frame(label = c("US", "GB", "BR"), val1=c(1,3,4), val2=c(23,12,32))
Line <- gvisLineChart(df, xvar="label", yvar=c("val1","val2"),
                      options=list(title="Hello World", legend="bottom",
                                   titleTextStyle="{color:'red', fontSize:18}",
                                   vAxis="{gridlines:{color:'red', count:3}}",
                                   hAxis="{title:'My Label',
                                          titleTextStyle:{color:'blue'}}",
                                   series="[{color:'green', targetAxisIndex: 0}, 
                                          {color: 'blue',targetAxisIndex:1}]",
                                   vAxes="[{title:'Value 1 (%)', format:'##,######%'}, 
                                          {title:'Value 2 (\U00A3)'}]",
                                   curveType="function", width=500, height=300
                                   ))

```

#Combining Multiple Plots Together

```{r}
G <- gvisGeoChart(Exports, "Country", "Profit", 
                  options=list(width=600, height=400))
T1 <- gvisTable(Exports, options=list(width=600, height=400))
M <- gvisMotionChart(Fruits, "Fruit", "Year", options = list(width=600, height=400))
GT <- gvisMerge(G, T1, horizontal = FALSE)
GTM <- gvisMerge(GT, M, horizontal= TRUE, tableOptions = "bgcolor=\"#CCCCCC\"")
```


